from __future__ import annotations

from queue import Queue
from typing import Any, Dict, List, Optional, Protocol


class StateRepositoryProtocol(Protocol):
    STREAM_CLOSED_EVENT: str
    ACTIVE_JOB_STATUSES: set[str]
    MAX_PERSISTED_JOB_EVENTS: int
    _state_root: Any

    def create_job(self, job: Dict[str, Any]) -> None: ...
    def update_job(self, job_id: str, job: Dict[str, Any]) -> None: ...
    def list_jobs(self, owner_user_id: Optional[str] = None) -> List[Dict[str, Any]]: ...
    def count_active_jobs(self, owner_user_id: Optional[str] = None) -> int: ...
    def count_active_detached_workers(self, owner_user_id: Optional[str] = None) -> int: ...
    def get_job(self, job_id: str, owner_user_id: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
    def set_assets(self, job_id: str, assets: Dict[str, Any]) -> None: ...
    def delete_job(self, job_id: str) -> None: ...
    def delete_jobs_for_user(self, owner_user_id: str) -> None: ...
    def get_assets(self, job_id: str) -> Optional[Dict[str, Any]]: ...
    def find_task(self, job_id: str, task_id: str, owner_user_id: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
    def get_job_event_cursor(self, job_id: str) -> Optional[str]: ...
    def read_job_events_since(self, job_id: str, cursor: Optional[str]) -> tuple[List[Dict[str, Any]], Optional[str]]: ...
    def publish_job_event(self, job_id: str, event_name: str, payload: Dict[str, Any]) -> None: ...
    def get_job_queue(self, job_id: str) -> Queue[Dict[str, Any]]: ...
    def subscribe_job_events(self, job_id: str) -> Queue[Dict[str, Any]]: ...
    def unsubscribe_job_events(self, job_id: str, subscriber_queue: Queue[Dict[str, Any]]) -> None: ...
    def create_chat_session(self, session: Dict[str, Any]) -> None: ...
    def list_chat_sessions(self, research_job_id: Optional[str] = None, owner_user_id: Optional[str] = None) -> List[Dict[str, Any]]: ...
    def get_chat_session(self, session_id: str, owner_user_id: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
    def get_latest_chat_session_for_job(self, research_job_id: str, owner_user_id: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
    def update_chat_session(self, session_id: str, session: Dict[str, Any], owner_user_id: Optional[str] = None) -> None: ...
    def append_chat_message(self, session_id: str, message: Dict[str, Any], owner_user_id: Optional[str] = None) -> Dict[str, Any]: ...
    def delete_chat_session(self, session_id: str) -> None: ...
    def delete_chat_sessions_for_user(self, owner_user_id: str) -> None: ...
    def create_user(self, user: Dict[str, Any]) -> None: ...
    def update_user(self, user_id: str, user: Dict[str, Any]) -> None: ...
    def get_user(self, user_id: str) -> Optional[Dict[str, Any]]: ...
    def delete_user(self, user_id: str) -> None: ...
    def find_user_by_email(self, email: str) -> Optional[Dict[str, Any]]: ...
    def list_users(self) -> List[Dict[str, Any]]: ...
    def count_users(self) -> int: ...
    def create_auth_session(self, auth_session: Dict[str, Any]) -> None: ...
    def get_auth_session(self, token_hash: str) -> Optional[Dict[str, Any]]: ...
    def update_auth_session(self, token_hash: str, auth_session: Dict[str, Any]) -> None: ...
    def delete_auth_session(self, token_hash: str) -> None: ...
    def delete_auth_sessions_for_user(self, user_id: str) -> None: ...
    def create_invite(self, invite: Dict[str, Any]) -> None: ...
    def update_invite(self, invite_id: str, invite: Dict[str, Any]) -> None: ...
    def get_invite(self, invite_id: str) -> Optional[Dict[str, Any]]: ...
    def list_invites(self, active_only: bool = False) -> List[Dict[str, Any]]: ...
    def find_invite_by_code(self, code: str) -> Optional[Dict[str, Any]]: ...
    def get_runtime_config(self, user_id: Optional[str] = None) -> Optional[Dict[str, Any]]: ...
    def get_auth_policy(self) -> Optional[Dict[str, Any]]: ...
    def delete_runtime_config(self, user_id: str) -> None: ...
    def set_runtime_config(self, runtime_config: Dict[str, Any], user_id: Optional[str] = None) -> None: ...
    def set_auth_policy(self, auth_policy: Dict[str, Any]) -> None: ...
    def supports_background_worker(self) -> bool: ...
    def enqueue_background_job(self, job_id: str) -> None: ...
    def dequeue_background_job(self, timeout_seconds: float = 1.0) -> Optional[str]: ...
